#le dice a docker que lo que este dentro de services son cada uno de los contenedores que voy a necesitar
services:
  #contenedor de la data base mysql
  mysql-db:
    image: mysql
    container_name: faster-envios-db
    restart: always
    # con esto aplico todas las varables de entorno que se necesiten para la ejecucion de la base de datos
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    #el mapeo de puertos
    ports:
        - "3307:3306"
    #esto ayuda para si el contenedor se llega a dañar o destruir no se pierd ala info porque crea una capreta con la nfo adentro
    volumes:
      - mysql_data:/var/lib/mysql
    #le dice a docker que meta el contenedor dentro de una red privada llamada envios-network
    networks:
      - envios-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend-service:
    # le digo que build porque no es una imagen que se descarga, es mi back que debe compilar
    build:
      #le digo l ruta donde esta mi back
      context: ./backEnd
      dockerfile: Dockerfile
    container_name: faster-envios-backend
    ports:
      - "8081:8080"
    #Aca señalo las variales de entorno para el uso del proyecto
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ORS_API_KEY=${ORS_API_KEY}
    #Le dice a docker que primero se debe iniciar la db y ahi s el proyecto o sea que el contenedor del back depende del contenedor de la db
    depends_on:
      mysql-db:
        condition: service_healthy
    #Mete al contenedor del back dentro de la network privada
    networks:
      - envios-network
  front-end:
    build:
      context: ./frontEnd
      dockerfile: Dockerfile
    container_name: faster-envios-frontend
    ports:
      - "3000:80"
    networks:
      - envios-network
volumes:
  mysql_data:
networks:
  envios-network:
    driver: bridge