spring:
  application:
    name: fasterEnvios
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    open-in-view: false

client:
  openRouteService-apiKey: ${ORS_API_KEY}

api:
  security:
    token:
      secret: ${JWT_SECRET}
      expiration: 86400