name: CI - FasterEnvios BackEnd
#aca le digo que esta action se ejecuta cuando se haga push a la rama main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
#aqui hago check out del codigo
      - name: Check del codigo del repositorio
        uses: actions/checkout@v4
      #aqui configuro java hago el set up
      - name: configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: construir maven esto ejecuta los tests internament
        run: mvn clean package
        working-directory: backEnd